// Generated by CoffeeScript 1.6.2
(function() {
  var todoItem;

  todoItem = (function() {
    todoItem.num = 0;

    function todoItem(descr, id, status) {
      switch (arguments.length) {
        case 1:
          this.description = descr;
          this.ID = todoItem.num++;
          this.isFinished = false;
          break;
        case 3:
          this.description = descr;
          this.ID = id;
          if (status === 'true' || status === 1) {
            this.isFinished = true;
          }
          this.isFinished = status;
          todoItem.num = (Math.max(todoItem.num, id)) + 1;
      }
    }

    todoItem.prototype.next = null;

    todoItem.prototype.info = function() {
      return this.ID + ": " + this.description + ": " + (this.isFinished ? "Finished" : "Not Finished");
    };

    todoItem.prototype.data = function() {
      return [this.ID, this.description, this.isFinished];
    };

    return todoItem;

  })();

  module.exports = todoItem;

}).call(this);
